version: "3"
services:
    portfolio:
        container_name: portfolio
        build: .
        # image: mikekorakakis/motobook:client-social
        environment:
            VIRTUAL_HOST: mike.korakakis.com
            LETSENCRYPT_HOST: mike.korakakis.com
            LETSENCRYPT_EMAIL: mike.korakakis@gmail.com
        #     args:
        #         NEXT_PUBLIC_AUTH0_DOMAIN: identity:5000
        ports:
            - "6000:3000"
        networks:
            - docker_nginx-proxy

    proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        restart: unless-stopped
        labels:s
            com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
            - certs:/etc/nginx/certs:rw
            - vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
        ports:
            - "80:80"
            - "443:443"

    proxy-letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: letsencrypt
        restart: unless-stopped
        environment:
            NGINX_PROXY_CONTAINER: proxy
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - certs:/etc/nginx/certs:rw
            - vhost.d:/etc/nginx/vhost.d
            - html:/usr/share/nginx/html
        depends_on:
            - "proxy"

volumes:
    db-data:
    docker_sock:
    certs:
    vhost.d:
    html:
# networks:
#     my-network:
#         ipam:
#             config:
#                 - subnet: 172.20.0.0/16
