---
# tasks file for user
- name: Ensure wheel group is present
  group:
    name: wheel
    state: present
- name: Ensure wheel group has sudo privileges
  lineinfile: 
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel" 
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Upgrading all packages (Ubuntu/Debian)
  apt:
    upgrade: dist
    update_cache: true
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"


- name: Install the `sudo` package
  package:
    name: sudo
    state: latest
- name: Create the non-root user account
  user:
    name: "{{ username }}"
    password: "{{ password }}"
    shell: /bin/bash
    update_password: on_create
    group: wheel

- name: Add SSH public key to the authorized_keys
  ansible.builtin.authorized_key:
    user: admin  # Replace with the target username
    state: present
    key: "{{ lookup('file', public_key) }}"
    path: "/home/admin/.ssh/authorized_keys"  # Replace with the correct path if different

# - name: Inserting a hosts in etc/hosts
#   blockinfile:
#     path: /etc/hosts
#     block: |
#       {{ host1 }}