---
# tasks file for ssh
# - name: Add local public key for key-based SSH authentication
#   authorized_key:
#     user: "{{ username }}"
#     state: present
#     key: "{{ lookup('file', '/home/mike/.ssh/id_rsa.pub') }}"

- name: Install OpenSSH server
  apt:
    name: openssh-server
    state: present
  when: ansible_os_family == "Debian"


- name: Harden sshd configuration
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{item.regexp}}"
    line: "{{item.line}}"
    state: present
  with_items:
    # - regexp: "^#?PermitRootLogin"
    #   line: "PermitRootLogin no"
    # - regexp: "^^#?PasswordAuthentication"
    #   line: "PasswordAuthentication no"
    - regexp: "^#?AllowAgentForwarding"
      line: "AllowAgentForwarding no"
    - regexp: "^#?AllowTcpForwarding"
      line: "AllowTcpForwarding no"
    - regexp: "^#?MaxAuthTries"
      line: "MaxAuthTries 2"
    - regexp: "^#?MaxSessions"
      line: "MaxSessions 2"
    - regexp: "^#?TCPKeepAlive"
      line: "TCPKeepAlive no"
    - regexp: "^#?UseDNS"
      line: "UseDNS no"
    - regexp: "^#?AllowAgentForwarding"
      line: "AllowAgentForwarding no"

- name: Gather service facts
  service_facts:

- name: Set SSH service name
  set_fact:
    ssh_service_name: "{{ 'ssh' if 'ssh.service' in ansible_facts.services else 'sshd' }}"


- name: Restart SSH service
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ ssh_service_name }}"
