name: Docker Push Images

on:
  workflow_dispatch:
    inputs:     
      use_docker:
        description: 'use docker scripts'
        default: 'no'
        required: false
      use_docker_ssl:
        description: 'use docker ssl'
        default: 'no'
        required: false

  
jobs:
  

  create_docker_ssl:
    runs-on: ubuntu-latest
    if:  github.event.inputs.use_docker_ssl=='yes' || github.event.inputs.use_docker_ssl=='y' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: delete docker compose folder
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port:  22 
          script: |         
            rm -rf Portfolio/
        
      - name: copy docker folder via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./ssl"
          target: "/home/${{ secrets.SERVER_USER }}/Portfolio"          

      - name: remote ssh apply docker scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port:  22 
          script: |
            docker-compose -f ./Portfolio/ssl/docker-compose.yml up -d 
  


  create_s:
    runs-on: ubuntu-latest
    if:  github.event.inputs.use_docker=='yes' || github.event.inputs.use_docker=='y' 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: delete docker compose folder
        uses: appleboy/ssh-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port:  22 
          script: |         
            rm -rf Portfolio/

        
      - name: copy docker folder via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./"
          target: "/home/${{ secrets.SERVER_USER }}/Portfolio"
        
      - name: remote ssh apply docker scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port:  22 
          script: |  
            docker-compose -f ./Portfolio/docker-compose.yml up -d 

  
